---

# If the matrix-synapse role is not used, `matrix_synapse_role_executed` won't exist.
# We don't want to fail in such cases.
- name: Fail if matrix-synapse role already executed
  fail:
    msg: >-
      The matrix-bridge-mautrix-wsproxy role needs to execute before the matrix-synapse role.
  when: "matrix_synapse_role_executed|default(False)"

- set_fact:
    matrix_mautrix_wsproxy_requires_restart: false

- name: Ensure Mautrix wsproxy image is pulled
  docker_image:
    name: "{{ matrix_mautrix_wsproxy_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_mautrix_wsproxy_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_mautrix_wsproxy_docker_image_force_pull }}"

- name: Ensure Mautrix wsproxy paths exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - "{{ matrix_mautrix_wsproxy_base_path }}"
    - "{{ matrix_mautrix_wsproxy_config_path }}"
    - "{{ matrix_mautrix_wsproxy_data_path }}"

- name: Check if an old matrix state file exists
  stat:
    path: "{{ matrix_mautrix_wsproxy_base_path }}/mx-state.json"
  register: matrix_mautrix_wsproxy_stat_mx_state

- name: Ensure mautrix-wsproxy config.yaml installed
  copy:
    content: "{{ matrix_mautrix_wsproxy_configuration|to_nice_yaml }}"
    dest: "{{ matrix_mautrix_wsproxy_config_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure mautrix-wsproxy registration.yaml installed
  copy:
    content: "{{ matrix_mautrix_wsproxy_registration|to_nice_yaml }}"
    dest: "{{ matrix_mautrix_wsproxy_config_path }}/registration.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Fail if matrix-nginx-proxy role already executed
  fail:
    msg: >-
      Trying to append mautrix-wsproxy reverse-proxying configuration to matrix-nginx-proxy,
      but it's pointless since the matrix-nginx-proxy role had already executed.
      To fix this, please change the order of roles in your plabook,
      so that the matrix-nginx-proxy role would run after the matrix-wspoxy role.
  when: matrix_nginx_proxy_role_executed|default(False)|bool and matrix_mautrix_wsproxy_enabled|bool

- name: Generate Wsproxy proxying configuration for matrix-nginx-proxy
  set_fact:
    matrix_mautrix_wsproxy_matrix_nginx_proxy_configuration: |
      location ~ ^/(_matrix/client/unstable/fi.mau.syncproxy/.*) {      
      {% if matrix_nginx_proxy_enabled|default(False) %}
        {# Use the embedded DNS resolver in Docker containers to discover the service #}
        resolver 127.0.0.11 valid=5s;
        set $backend "matrix-mautrix-wsproxy:{{ matrix_mautrix_wsproxy_port }}/$1";
        proxy_pass http://$backend;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      {% else %}
        {# Generic configuration for use outside of our container setup #}
        proxy_pass http://127.0.0.1:{{ matrix_mautrix_wsproxy_port }}/$1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      {% endif %}
      }

  when: matrix_mautrix_wsproxy_enabled|bool

- name: Register Wsproxy's proxying configuration with matrix-nginx-proxy
  set_fact:
    matrix_nginx_proxy_proxy_matrix_additional_server_configuration_blocks: |
      {{
        matrix_nginx_proxy_proxy_matrix_additional_server_configuration_blocks|default([])
        +
        [matrix_bot_maubot_matrix_nginx_proxy_configuration]
      }}
  when: matrix_mautrix_wsproxy_enabled|bool

- name: Warn about reverse-proxying if matrix-nginx-proxy not used
  debug:
    msg: >-
      NOTE: You've enabled mautrix-wsproxy but are not using the matrix-nginx-proxy
      reverse proxy.
      Please make sure that you're proxying the `/_matrix/client/unstable/fi.mau.syncproxy`
      URL endpoint to the mautrix-wsproxy container.
  when: "matrix_mautrix_wsproxy_enabled|bool and matrix_nginx_proxy_enabled is not defined"

- name: Ensure matrix-mautrix-wsproxy.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-mautrix-wsproxy.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-mautrix-wsproxy.service"
    mode: 0644
  register: matrix_mautrix_wsproxy_systemd_service_result

- name: Ensure systemd reloaded after matrix-mautrix-wsproxy.service installation
  service:
    daemon_reload: yes
  when: "matrix_mautrix_wsproxy_systemd_service_result.changed"

- name: Ensure matrix-mautrix-wsproxy.service restarted, if necessary
  service:
    name: "matrix-mautrix-wsproxy.service"
    state: restarted
  when: "matrix_mautrix_wsproxy_requires_restart|bool"
